[package]
name = "advent-of-code-2019-8"
version = "0.1.0"
authors = ["Heiner Tholen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cute = "0.3.0"
